/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.inicio;

import vista.consulta.*;


/**
 *
 * @author Nico
 */
public class VAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public VAdministracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAdmProveedor = new javax.swing.JButton();
        btAdmCliente = new javax.swing.JButton();
        btAdmProducto = new javax.swing.JButton();
        btAdmUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btAdmProveedor.setText("Proveedores");
        btAdmProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmProveedorActionPerformed(evt);
            }
        });

        btAdmCliente.setText("Clientes");
        btAdmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmClienteActionPerformed(evt);
            }
        });

        btAdmProducto.setText("Productos");
        btAdmProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmProductoActionPerformed(evt);
            }
        });

        btAdmUsuario.setText("Usuarios");
        btAdmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdmUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btAdmProducto)
                        .addComponent(btAdmProveedor)
                        .addComponent(btAdmCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAdmUsuario)
                        .addGap(22, 22, 22)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btAdmProducto)
                .addGap(70, 70, 70)
                .addComponent(btAdmProveedor)
                .addGap(63, 63, 63)
                .addComponent(btAdmCliente)
                .addGap(66, 66, 66)
                .addComponent(btAdmUsuario)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdmProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmProductoActionPerformed
        VConsultaProducto vistaProducto = new VConsultaProducto();
        vistaProducto.setVisible(true);
    }//GEN-LAST:event_btAdmProductoActionPerformed

    private void btAdmProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmProveedorActionPerformed
        VConsultaProveedor vistaProveedor = new VConsultaProveedor();
        vistaProveedor.setVisible(true);
    }//GEN-LAST:event_btAdmProveedorActionPerformed

    private void btAdmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmClienteActionPerformed
        VConsultaCliente vistaCliente = new VConsultaCliente();
        vistaCliente.setVisible(true);
    }//GEN-LAST:event_btAdmClienteActionPerformed

    private void btAdmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdmUsuarioActionPerformed
        VConsultaUsuario vistaUsuario = new VConsultaUsuario();
        vistaUsuario.setVisible(true);
    }//GEN-LAST:event_btAdmUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdministracion().setVisible(true);
            }
        });
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdmCliente;
    private javax.swing.JButton btAdmProducto;
    private javax.swing.JButton btAdmProveedor;
    private javax.swing.JButton btAdmUsuario;
    // End of variables declaration//GEN-END:variables
}
