package modelo.pojo;
// Generated 22/05/2017 01:38:15 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String codCliente;
     private String nombre;
     private String direccion;
     private String codigoPostal;
     private String telefono;
     private String dni;
     private Double saldo;

    public Cliente() {
    }

	
    public Cliente(String codCliente) {
        this.codCliente = codCliente;
    }
    public Cliente(String codCliente, String nombre, String direccion, String codigoPostal, String telefono, String dni, Double saldo) {
       this.codCliente = codCliente;
       this.nombre = nombre;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.telefono = telefono;
       this.dni = dni;
       this.saldo = saldo;
    }
   
    public String getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }




}


