package modelo.pojo;
// Generated 22/05/2017 04:20:50 by Hibernate Tools 4.3.1



/**
 * Listaprecioproducto generated by hbm2java
 */
public class Listaprecioproducto  implements java.io.Serializable {


     private ListaprecioproductoId id;

    public Listaprecioproducto() {
    }

    public Listaprecioproducto(ListaprecioproductoId id) {
       this.id = id;
    }
   
    public ListaprecioproductoId getId() {
        return this.id;
    }
    
    public void setId(ListaprecioproductoId id) {
        this.id = id;
    }




}


