package modelo.pojo;
// Generated 27/07/2017 15:38:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Listaprecioproducto generated by hbm2java
 */
public class Listaprecioproducto  implements java.io.Serializable {


     private Integer idlista;
     private String codigoProducto;
     private Double precio;
     private Date fecha;

    public Listaprecioproducto() {
    }

    public Listaprecioproducto(String codigoProducto, Double precio, Date fecha) {
       this.codigoProducto = codigoProducto;
       this.precio = precio;
       this.fecha = fecha;
    }
    
    public Listaprecioproducto(Integer idlista, String codigoProducto, Double precio, Date fecha) {
       this.idlista = idlista;
       this.codigoProducto = codigoProducto;
       this.precio = precio;
       this.fecha = fecha;
    }
   
    public Integer getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(Integer idlista) {
        this.idlista = idlista;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


