package modelo.pojo;
// Generated 22/05/2017 04:20:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ListaprecioproductoId generated by hbm2java
 */
public class ListaprecioproductoId  implements java.io.Serializable {


     private String codigoProducto;
     private Double precio;
     private Date fecha;

    public ListaprecioproductoId() {
    }

    public ListaprecioproductoId(String codigoProducto, Double precio, Date fecha) {
       this.codigoProducto = codigoProducto;
       this.precio = precio;
       this.fecha = fecha;
    }
   
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ListaprecioproductoId) ) return false;
		 ListaprecioproductoId castOther = ( ListaprecioproductoId ) other; 
         
		 return ( (this.getCodigoProducto()==castOther.getCodigoProducto()) || ( this.getCodigoProducto()!=null && castOther.getCodigoProducto()!=null && this.getCodigoProducto().equals(castOther.getCodigoProducto()) ) )
 && ( (this.getPrecio()==castOther.getPrecio()) || ( this.getPrecio()!=null && castOther.getPrecio()!=null && this.getPrecio().equals(castOther.getPrecio()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodigoProducto() == null ? 0 : this.getCodigoProducto().hashCode() );
         result = 37 * result + ( getPrecio() == null ? 0 : this.getPrecio().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


