package modelo.pojo;
// Generated 22/05/2017 01:38:15 by Hibernate Tools 4.3.1


import java.util.Calendar;
import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;
     private Date fecha;
     private Double precio;
     private Integer stock;
     private String proveedor;
     private String rubro;
     private String subRubro;
     private Boolean estado;
     private Date fechaModificacion;

    public Producto() {
    }

	
    public Producto(String codigo) {
        this.codigo = codigo;
    }
    public Producto(String codigo, String nombre, String descripcion, Double precio, String proveedor, String rubro, String subRubro) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
      // this.fecha = fechaDeHoy();
       this.precio = precio;
       this.stock = 0;
       this.proveedor = proveedor;
       this.rubro = rubro;
       this.subRubro = subRubro;
       this.estado = true;
      // this.fechaModificacion = fechaDeHoy();
    }
   
   
    
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }
    public String getSubRubro() {
        return this.subRubro;
    }
    
    public void setSubRubro(String subRubro) {
        this.subRubro = subRubro;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


