package modelo.pojo;
// Generated 27/07/2017 15:38:07 by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer codigo;
     private String nombre;
     private String direccion;
     private Integer cp;
     private String telefono;
     private String cuit;

    public Proveedor() {
    }

    public Proveedor(String nombre, String direccion, Integer cp, String telefono, String cuit) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.cp = cp;
       this.telefono = telefono;
       this.cuit = cuit;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }




}


