package modelo.pojo;
// Generated 22/05/2017 01:38:15 by Hibernate Tools 4.3.1



/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String codProveedor;
     private String nombre;
     private String direccion;
     private String codigoPostal;
     private String telefono;
     private String cuit;

    public Proveedor() {
    }

	
    public Proveedor(String codProveedor) {
        this.codProveedor = codProveedor;
    }
    public Proveedor(String codProveedor, String nombre, String direccion, String codigoPostal, String telefono, String cuit) {
       this.codProveedor = codProveedor;
       this.nombre = nombre;
       this.direccion = direccion;
       this.codigoPostal = codigoPostal;
       this.telefono = telefono;
       this.cuit = cuit;
    }
   
    public String getCodProveedor() {
        return this.codProveedor;
    }
    
    public void setCodProveedor(String codProveedor) {
        this.codProveedor = codProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }




}


